### ISSUE TITLE
gamemoderun %command% does not start the game

### ISSUE THREAD

**Issue by lordgault** [FeralInteractive/gamemode#117] opened 2019-03-17 07:29 UTC
By adding gamemoderun %command% in the Stean launch options the game does not start. I have to keep using LD_PRELOAD=$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so.0 %command% 

**To Reproduce**
Steps used to reproduce the behavior:
1. Go to launch options for any Steam game.
2. Enter  gamemoderun %command%.
3. Start game.
4. The game doesn't start.

**System Info :**
 - Ubuntu 18.04
 - GameMode Version 1.3

**Additional context**
Information on console.
```
>>> Adding process 9977 for game ID 367520
GameAction [AppID 367520, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/patrick/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: 1: gamemoderun: Permission denied
GameAction [AppID 367520, ActionID 1] : LaunchApp changed task to Completed with ""
>>> Adding process 9978 for game ID 367520
Game removed: AppID 367520 "", ProcID 9977 
```

**Comment by mdiluz** [comment] 2019-03-17 08:50
Looks like a duplicate of #113

**Comment by lordgault** [comment] 2019-03-17 17:03
Yes, giving `sudo chmod +x /usr/bin/gamemoderun` permissions solved the problem. Now the game runs and gamemode changes the governor.

**Comment by aejsmith** [comment] 2019-03-25 16:30
I'll close this and use #115 to track this.

**Closed by aejsmith** 2019-03-25 16:30 UTC
