### ISSUE TITLE
bootstrap.sh fails on ubuntu 16.04

### ISSUE THREAD

**Issue by dimitra86** [FeralInteractive/gamemode#34] opened 2018-04-16 14:38 UTC
Hi, I have followed the steps to install and I get to this error:
user@u16:~/gamemode-1.0$ ./bootstrap.sh
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.40.1
Source dir: /home/user/gamemode-1.0
Build dir: /home/user/gamemode-1.0/build
Build type: native build
Project name: gamemode
Native c compiler: cc (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 229
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration

Executing subproject inih.

Project name: inih
Native c compiler: cc (gcc 5.4.0)
Build targets in project: 3

Subproject inih finished.
Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Message: 

    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib/x86_64-linux-gnu
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    daemon:                                 true
    examples:                               true
    systemd:                                true

Build targets in project: 7
+ cd build
+ ninja
[4/20] Compiling c object 'daemon/gamemoded@exe/dbus_messaging.c.o'
FAILED: daemon/gamemoded@exe/dbus_messaging.c.o 
cc  '-Idaemon/gamemoded@exe' '-Idaemon' '-I../daemon' '-I.' '-I../' '-Isubprojects/inih' '-I../subprojects/inih' '-fdiagnostics-color=always' '-pipe' '-D_FILE_OFFSET_BITS=64' '-Wall' '-Winvalid-pch' '-std=c11' '-O0' '-g' '-fstack-protector' '-Wall' '-pedantic' '-Wstrict-prototypes' '-Wundef' '-fno-common' '-Werror-implicit-function-declaration' '-Wformat' '-Wformat-security' '-Werror=format-security' '-Wconversion' '-Wunused-variable' '-Wunreachable-code' '-W' '-pthread' '-MMD' '-MQ' 'daemon/gamemoded@exe/dbus_messaging.c.o' '-MF' 'daemon/gamemoded@exe/dbus_messaging.c.o.d' -o 'daemon/gamemoded@exe/dbus_messaging.c.o' -c ../daemon/dbus_messaging.c
In file included from /usr/include/systemd/sd-bus.h:28:0,
                 from ../daemon/dbus_messaging.c:40:
/usr/include/systemd/sd-event.h:72:67: error: unknown type name ‘siginfo_t’
 typedef int (*sd_event_child_handler_t)(sd_event_source *s, const siginfo_t *si, void *userdata);
                                                                   ^
[5/20] Compiling c object 'lib/gamemode@sha/client_impl.c.o'
FAILED: lib/gamemode@sha/client_impl.c.o 
cc  '-Ilib/gamemode@sha' '-Ilib' '-I../lib' '-fdiagnostics-color=always' '-pipe' '-D_FILE_OFFSET_BITS=64' '-Wall' '-Winvalid-pch' '-std=c11' '-O0' '-g' '-fstack-protector' '-Wall' '-pedantic' '-Wstrict-prototypes' '-Wundef' '-fno-common' '-Werror-implicit-function-declaration' '-Wformat' '-Wformat-security' '-Werror=format-security' '-Wconversion' '-Wunused-variable' '-Wunreachable-code' '-W' '-fPIC' '-MMD' '-MQ' 'lib/gamemode@sha/client_impl.c.o' '-MF' 'lib/gamemode@sha/client_impl.c.o.d' -o 'lib/gamemode@sha/client_impl.c.o' -c ../lib/client_impl.c
In file included from /usr/include/systemd/sd-bus.h:28:0,
                 from ../lib/client_impl.c:36:
/usr/include/systemd/sd-event.h:72:67: error: unknown type name ‘siginfo_t’
 typedef int (*sd_event_child_handler_t)(sd_event_source *s, const siginfo_t *si, void *userdata);
                                                                   ^
[13/20] Compiling c object 'daemon/daemon-common@sta/governors-query.c.o'
ninja: build stopped: subcommand failed.

**Comment by mdiluz** [comment] 2018-04-17 14:34
Could you try the master branch with git? On a fresh install of Xenial (with backports activated for meson/ninja versions) I only have this issue with the `1.0` tag.

**Comment by dimitra86** [comment] 2018-04-17 15:41
**I created a gamemode folder and cloned the repository and I get to this error:**
user@u16:~/gamemode2$ ./bootstrap.sh
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.40.1
Source dir: /home/user/gamemode2
Build dir: /home/user/gamemode2/build
Build type: native build
Project name: gamemode
Native c compiler: cc (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 229
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration

Meson encountered an error in file meson.build, line 86, column 4:
Subproject directory 'subprojects/inih' does not exist and cannot be downloaded:
No inih.wrap found for 'subprojects/inih'


**Then I copied the folder "subprojects" from gamemode-1.0 and I get to this error:**
user@u16:~/gamemode$ ./bootstrap.sh
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.40.1
Source dir: /home/user/gamemode
Build dir: /home/user/gamemode/build
Build type: native build
Project name: gamemode
Native c compiler: cc (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 229
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration

Executing subproject inih.

Project name: inih
Native c compiler: cc (gcc 5.4.0)
Build targets in project: 3

Subproject inih finished.
Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Message: 


    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib/x86_64-linux-gnu
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    daemon:                                 true
    examples:                               true
    systemd:                                true


Build targets in project: 7
+ cd build
+ ninja
[20/20] Linking target daemon/gamemoded
+ set +x
Install to /usr? [Yy] y
+ sudo ninja install
[sudo] пароль для user: 
[0/1] Installing files.
Installing lib/libgamemode.so to /usr/lib/x86_64-linux-gnu/libgamemode.so
Installing lib/libgamemodeauto.so to /usr/lib/x86_64-linux-gnu/libgamemodeauto.so
Installing daemon/gamemoded to /usr/bin/gamemoded
Installing daemon/cpugovctl to /usr/libexec/cpugovctl
Installing gamemode_client.h to /usr/include/
Installing /home/user/gamemode/data/gamemoded.1 to /usr/share/man/man1
Installing /home/user/gamemode/build/data/gamemoded.service to /etc/systemd/user
Installing /home/user/gamemode/build/data/com.feralinteractive.GameMode.policy to /usr/share/polkit-1/actions
+ set +x
Enable and run the daemon? [Yy] y
+ systemctl --user daemon-reload
+ systemctl --user enable gamemoded
Created symlink from /home/user/.config/systemd/user/default.target.wants/gamemoded.service to /etc/systemd/user/gamemoded.service.
+ systemctl --user start gamemoded
Failed to start gamemoded.service: Unit dbus.socket not found.

**Comment by mdiluz** [comment] 2018-04-17 15:43
I'm unsure why you needed to copy over the subprojects folder, perhaps you have a git option to ignore submodules?

Either way, the second issue should be fixed by installing `dbus-user-session` and rebooting.

**Comment by dimitra86** [comment] 2018-04-17 17:14
> I'm unsure why you needed to copy over the subprojects folder,
Because this folder was empty.

> Either way, the second issue should be fixed by installing dbus-user-session and rebooting.
Yes it works.

user@u16:~/gamemode$ ./bootstrap.sh
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.40.1
Source dir: /home/user/gamemode
Build dir: /home/user/gamemode/build
Build type: native build
Project name: gamemode
Native c compiler: cc (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 229
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration

Executing subproject inih.

Project name: inih
Native c compiler: cc (gcc 5.4.0)
Build targets in project: 3

Subproject inih finished.
Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Message: 


    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib/x86_64-linux-gnu
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    daemon:                                 true
    examples:                               true
    systemd:                                true


Build targets in project: 7
+ cd build
+ ninja
[20/20] Linking target daemon/gamemoded
+ set +x
Install to /usr? [Yy] y
+ sudo ninja install
[sudo] пароль для user: 
[0/1] Installing files.
Installing lib/libgamemode.so to /usr/lib/x86_64-linux-gnu/libgamemode.so
Installing lib/libgamemodeauto.so to /usr/lib/x86_64-linux-gnu/libgamemodeauto.so
Installing daemon/gamemoded to /usr/bin/gamemoded
Installing daemon/cpugovctl to /usr/libexec/cpugovctl
Installing gamemode_client.h to /usr/include/
Installing /home/user/gamemode/data/gamemoded.1 to /usr/share/man/man1
Installing /home/user/gamemode/build/data/gamemoded.service to /etc/systemd/user
Installing /home/user/gamemode/build/data/com.feralinteractive.GameMode.policy to /usr/share/polkit-1/actions
+ set +x
Enable and run the daemon? [Yy] y
+ systemctl --user daemon-reload
+ systemctl --user enable gamemoded
+ systemctl --user start gamemoded
+ systemctl --user status gamemoded
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; enabled; vendor preset: 
   Active: active (running) since Вт 2018-04-17 20:07:44 +03; 1min 13s ago
 Main PID: 1303 (gamemoded)
   Status: "GameMode is ready to be activated."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─1303 /usr/bin/gamemoded -l

апр 17 20:07:43 u16 systemd[1296]: Starting gamemoded...
апр 17 20:07:44 u16 /usr/bin/gamemoded[1303]: Note: No config file found [gamemo
апр 17 20:07:44 u16 /usr/bin/gamemoded[1303]: governor is set to [performance]
апр 17 20:07:44 u16 /usr/bin/gamemoded[1303]: Successfully initialised bus with 
апр 17 20:07:44 u16 systemd[1296]: Started gamemoded.
апр 17 20:08:57 u16 systemd[1296]: Started gamemoded.
...skipping...
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; enabled; vendor preset: 
   Active: active (running) since Вт 2018-04-17 20:07:44 +03; 1min 13s ago
 Main PID: 1303 (gamemoded)
   Status: "GameMode is ready to be activated."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─1303 /usr/bin/gamemoded -l

апр 17 20:07:43 u16 systemd[1296]: Starting gamemoded...
апр 17 20:07:44 u16 /usr/bin/gamemoded[1303]: Note: No config file found [gamemo
апр 17 20:07:44 u16 /usr/bin/gamemoded[1303]: governor is set to [performance]
апр 17 20:07:44 u16 /usr/bin/gamemoded[1303]: Successfully initialised bus with 
апр 17 20:07:44 u16 systemd[1296]: Started gamemoded.
апр 17 20:08:57 u16 systemd[1296]: Started gamemoded.

**Comment by mdiluz** [comment] 2018-04-18 08:31
Thanks, @dimitra86, glad it now works.

> Because this folder was empty.

So the thing is it shouldn't be empty, meson should be handling checking it out. See [.gitmodules](https://github.com/FeralInteractive/gamemode/blob/master/.gitmodules).

If the problem still persists for you on a fresh clone, could you try these two commands?
```
git submodule init
git submodule update
```

[This PR](https://github.com/mesonbuild/meson/pull/1516/commits/a60d688973e8903015f6e4b157332c5c98562f55) added this functionality to meson, which appears to be in the 0.40.1 tag branch, so I'm unsure why it's not working for you I'm afraid.

**Comment by alexsmithfanning** [comment] 2018-04-30 01:32
For anybody that installed `dbus-user-session` and have noticed that Google Chrome does not work, **it is a known issue**. There's a workaround that involves running `gnome-keyring-daemon &` manually. You could also try **uninstalling** `dbus-user-session` but then it might break `gamemode`.

**Comment by unmellow** [comment] 2018-05-02 17:37
just wanted to say that this issue and https://github.com/FeralInteractive/gamemode/issues/32 should be merged sense Linux mint 18.3 is based off ubuntu 16.4 so the issue is probably the same

**Comment by mdiluz** [comment] 2018-05-11 08:12
Yeah, that's a fair point @unmellow, I'll close this one and add to the title of the other

**Closed** 2018-05-11 08:12 UTC
