### ISSUE TITLE
Supervisor tests fail

### ISSUE THREAD

**Issue by jul-ben** [FeralInteractive/gamemode#176] opened 2019-12-08 02:02 UTC
**Describe the bug**
Tests fail when running them.

**To Reproduce**
Steps used to reproduce the behavior:
1. Use git to clone the repository
2. Build it like said in README.md
3. Install gamemode in /usr
4. Run the command "gamemoded -t"

**Expected behavior**
I should all the test being done successfully.

**System Info (please complete the following information):**
 - OS and version: Debian 10 (Buster)
 - GameMode Version 1.3-dev

**Standard output**
$ gamemoded -t
: Loading config
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
ERROR: gamemode_query_status after start request gave unexpected value 2, (expected 1)!
ERROR: :: Failed!
: Client tests failed, skipping feature tests
: Tests Failed!

**Comment by stephanlachnit** [comment] 2020-05-20 08:20
I can still reproduce this with 1.5.1 on Debian Sid:
```
$ gamemoded --test

: Loading config
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
ERROR: failed to launch gamemoderun with execl: No such file or directory
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
ERROR: gamemode failed to deactivate when requested (expected 0)!
:: Supervisor tests
ERROR: gamemode_query_status after start request gave unexpected value 2, (expected 1)!
ERROR: gamemode_query_status after end request gave unexpected value 1, (expected 0)!
ERROR: :: Failed!
: Client tests failed, skipping feature tests
: Tests Failed!
```

**Comment by stephanlachnit** [comment] 2020-06-16 14:53
Can anyone reproduce this error? But I can't reproduce it.
My problem before was that I didn't have gamemoderun installed in `/usr/bin`:
```
ERROR: failed to launch gamemoderun with execl: No such file or directory
```
Now the tests run fine for me.

**Comment by at46** [comment] 2020-06-18 16:51
@stephanlachnit I still have the bug you mention above with `ERROR: failed to launch gamemoderun with execl: No such file or directory` on debian testing/sid. gamemoderun is in /usr/game not /usr/bin https://packages.debian.org/sid/amd64/gamemode/filelist. Is taht a Debian bug?

**Comment by stephanlachnit** [comment] 2020-06-18 16:57
Yes this is a Debian "bug" (it's actually intended), I'm aware that the different location breaks this test. You can create a symlink from `/usr/bin/gamemoderun` to `/usr/games/gamemoderun` to test it. I'll probably write a small patch to change the path once the next gamemode version is released.
In a perfect world the path wouldn't be set explicitly but rather configured via Meson, if you want to do that go for it.

**Comment by at46** [comment] 2020-06-18 17:07
I created the symlink and now all tests pass.

**Comment by stephanlachnit** [comment] 2020-06-19 08:16
@jul-ben can you retry this?
@afayaz-feral since this isn't reproducible I guess it can be removed from the milestone.

**Comment by afayaz-feral** [comment] 2020-07-17 16:28
Closing. @jul-ben feel free to reopen if you're still having a problem.

**Comment by jul-ben** [comment] 2020-07-18 18:52
Sorry, I should have answered sooner: long story short, it happened on Debian 9, not happening again on Debian 10.

I do not know what was the issue though.

**Closed** 2020-07-18 18:53 UTC
Labels: bug
