### ISSUE TITLE
Setting process to SCHED_ISO fails with error 1

### ISSUE THREAD

**Issue by terencode** [FeralInteractive/gamemode#68] opened 2018-07-21 19:25 UTC
**Describe the bug**
My kernel provides SCHED_ISO and gamemode detects it but fails to apply it: 
>"Setting client [22578] to SCHED_ISO failed with error 1, ignoring"

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch gamemod with a kernel providing SCHED_ISO
2. Run any game
3. View output of journalctl /usr/bin/gamemoded
4. See error "Setting client [PID] to SCHED_ISO failed with error 1, ignoring"

**Expected behavior**
Gamemode should be able to set the process to SCHED_ISO
**System Info:**
 - OS and version: ArchLinux 4.17.6-1-lqx
 - GameMode Version 1.2

**Additional context**
I would think this is a permission/configuration problem.

**Comment by VanackSabbadium** [comment] 2018-07-22 19:17
I've got the same problem, and i also add that GameMode can't renice processes.

`Renicing client [3499] failed with error 13, ignoring.`

**Comment by aejsmith** [comment] 2018-07-23 09:09
Renicing will likely fail by default due to permissions. You need to configure `/etc/security/limits.conf` to allow regular users to raise the priority.

I'm not sure if you need to do similar with `SCHED_ISO` - @kakra do you know if there's anything you need to do permissions-wise for it to work?

**Comment by kakra** [comment] 2018-07-23 09:32
`SCHED_ISO` is to my best knowledge not privileged because it's safe to use (it does not dominate or destabilize the system). Still, errno = 1 means `EPERM`. I don't think this is a permission error by the user lacking permission (this would result in errno = 13, `EACCES`) but the operation is simply not permitted by system restrictions. This usually indicates a missing feature or unavailable due to configuration.

@terencode Did you compile the kernel with `CONFIG_SCHED_MUQSS=y`? It is not sufficient to just patch the kernel with the CK patchset and then recompile. You must reconfigure to enable MuQSS which is the feature that actually makes `SCHED_ISO` available.

BTW @VanackSabbadium You probably need to restart your session after adjusting pam limits. Otherwise, the limits aren't loaded into the current session and you won't be able to use them.

**Comment by kakra** [comment] 2018-07-23 09:39
@terencode Can you run `schedtool -I -e /path/to/game/exe` and see if it complains? It should work out of the box if your kernel has the required configuration and schedtool is new enough.

**Comment by kakra** [comment] 2018-07-23 09:42
@aejsmith Let's see how this works out. I could imagine that with latest systemd, there's a syscall filter in place which prevents setting foreign PIDs to a different scheduler. Current systemd defaults to whitelisting syscalls instead of blacklisting so we may need to whitelist the syscalls in the service unit file.

**Comment by kakra** [comment] 2018-07-23 09:58
Sorry for the noise, I've searched a little: People without CK patchset usually see errno = 22 `EINVAL` indicating an invalid argument. This pushes me towards thinking it's a syscall filtering issue. I'm not using it a systemd daemon here currently, so I cannot currently reproduce this.

Steps to narrow it down include:

1. Check if `schedtool -I` works instead, this would confirm availability.
2. Run `systemd-analyse syscall-filter` and look for `sched_setscheduler`. Which section is it in?

In 2, if not in `@default`, you need to add the syscall to the whitelist of the service. For me, it's shown in `@resources` but you do not need to whitelist the whole group, the single syscall is sufficient. But I'm not sure if whitelisting syscalls outside of the system-provided service files is allowed. That means, your changes have to be in `/usr/lib/systemd`, `/lib/systemd`, or maybe `/etc/systemd`. Otherwise, changing syscall filters may not be permitted and ignored.

BTW: Renice may suffer the same issue.

@VanackSabbadium I think your problem should be a separate issue because it does not show errno = 1.

**Comment by terencode** [comment] 2018-07-23 14:05
@kakra Thanks for the tips, schedtool -I works, so it's available for me.
`systemd-analyze syscall-filter`tells me it's in `@resources`.

**Comment by kakra** [comment] 2018-07-23 15:21
@terencode Find the location of the `gamemoded.service` file, it should be in `/usr/lib/systemd/user`, maybe in `/lib/systemd/user`.

Open the file, and add the following line in the `[Service]` block:

    SystemCallFilter=sched_setscheduler

Now reload the user daemon and restart the service so it grabs the new changes:

    systemctl --user daemon-reload
    systemctl --user restart gamemoded.service

Alternatively, reboot.

I'm not sure if this is sufficient. Please let us know if this solves your issue or if you still see errors. The complete output of the following commands could be helpful after firing the daemon up and running a supported game:

    journalctl --user -b -u gamemoded.service
    systemctl --user show gamemoded.service

**Comment by terencode** [comment] 2018-07-23 15:31
@kakra I have a big problem... Somehow gamemoded is infected:
``juil. 23 17:27:46 terence-arch /usr/bin/gamemoded[2392]: Executing script [/home/me/bin/start_ethmining.sh]
juil. 23 17:27:46 terence-arch gamemoded[2392]: sh: /home/me/bin/start_ethmining.sh: Aucun fichier ou dossier de ce type
juil. 23 17:27:46 terence-arch /usr/bin/gamemoded[2392]: Script [/home/me/bin/start_ethmining.sh] failed with error 32512
``

**Comment by kakra** [comment] 2018-07-23 15:35
@terencode It may be possible that `SystemCallFilter` triggers undesired behavior if you already added this configuration. It may lead to children processes terminating with `SIGSYS` upon stepping on a disallowed syscall. You can revert the change and we need to find a more complete solution.

You should be able to see non-default termination signals in the output of `dmesg`.

**Comment by terencode** [comment] 2018-07-23 15:39
@kakra I checked if this entry corresponds to me adding SystemCallFilter but it seems it does not. This error was also reported yesterday. Once I sort this problem out, I'll tell you if your proposed approach works. Thanks for the info.

**Comment by terencode** [comment] 2018-07-23 15:41
@kakra this seems to not be as alarming as I thought, it's probably due to https://github.com/FeralInteractive/gamemode/commit/d26aac7147efe732c82c76074156bda66eda9ac3

**Comment by kakra** [comment] 2018-07-23 15:42
Chances are that you simply used the default configuration file. I'd start with an empty configuration file.

**Comment by terencode** [comment] 2018-07-23 15:46
@kakra 

>  It may be possible that SystemCallFilter triggers undesired behavior if you already added this configuration. It may lead to children processes terminating with SIGSYS upon stepping on a disallowed syscall

Indeed, this is what is happening
>PS: Did you run as root?
No.

(Can I remove my previous comments as they are not relevant to this issue ?)

**Comment by terencode** [comment] 2018-07-23 16:04
@kakra using
`SystemCallFilter=@system-service sched_setscheduler

Doesn't make it crash but it doesn't fix the error when trying to set SCHED_ISO so this setting is probably not the right approach.

**Comment by aejsmith** [comment] 2018-07-23 16:13
I've commented out the custom scripts in the example configuration file (34ea576). Probably a little alarming to see "start_ethmining.sh" if you copy that configuration without modification :)

**Comment by VanackSabbadium** [comment] 2018-07-23 20:23
Thank you everybody, i solved my issue with renice adding this line to /usr/security/limits.conf file and rebooting:

`myusername - nice -20`

However, i think my kernel does not support SCHED_ISO, which gives me error 22.

**Comment by kakra** [comment] 2018-07-25 23:18
@VanackSabbadium Actually, setting a process to `SCHED_ISO` will make it ignore the nice value because it runs under different scheduling assumptions then. So even without `SCHED_ISO` you still benefit from renicing. `SCHED_ISO` will give a process real-time like behavior as long as its total avg CPU usage across all cores and the last 5 seconds won't go above 70% - which is unlikely for today multi-core CPUs and current games. But when it passes the threshold, it will fall back to normal scheduling and consider the nice value. This is also why I put heuristics into it to only use `SCHED_ISO` with at least 4 cores. A game would need to fully utilize three cores then for 5s before passing the 70% threshold.

**Comment by VanackSabbadium** [comment] 2018-07-26 04:06
Alright, i don't understand a single word of what you're saying (my bad, not your fault).
However, i'll focus on the only thing i understand, that is:

> Actually, setting a process to SCHED_ISO will make it ignore the nice value because it runs under different scheduling assumptions then. So even without SCHED_ISO you still benefit from renicing.

That's enough for me XD

**Comment by kakra** [comment] 2018-10-03 16:00
Anyone still having issues or can we close this?

**Comment by terencode** [comment] 2018-10-03 16:32
This is still an issue for me.
My kernel has SCHED_ISO capability but gamemode says
``Setting client [26036] to SCHED_ISO failed with error 1, ignoring (your kernel may not support this).``

**Comment by terencode** [comment] 2018-10-03 16:37
The daemon is running as a user unit. Would not this be the cause?

**Comment by kakra** [comment] 2018-10-03 16:50
Could you share your running kernel config and version?

**Comment by terencode** [comment] 2018-10-03 16:53
here you go: 
[kernel_config.txt](https://github.com/FeralInteractive/gamemode/files/2442935/kernel_config.txt)

**Comment by kakra** [comment] 2018-10-03 17:13
This looks fine so far. Which distribution is this? And could you also share `systemctl --user show gamemoded.service`?

If you stop the daemon and just run it on the command line, then start a game, will it work then? This would rule out problems introduces through systemd.

**Comment by terencode** [comment] 2018-10-03 17:14
Same as when I opened the issue: ArchLinux.
>systemctl --user show gamemoded.service: 
[gamemoded.txt](https://github.com/FeralInteractive/gamemode/files/2443008/gamemoded.txt)

**Comment by terencode** [comment] 2018-10-03 17:17
Same when running on the command line:

> >> gamemoded                                                                                                                                                                            
> v1.3-dev
> Loading config file [/home/terence/.config/gamemode.ini]
> Successfully initialised bus with name [com.feralinteractive.GameMode]...
> Adding game: 24999 [/opt/SteamLibrary/steamapps/common/Natural Selection 2/x64/ns2_linux]
> Entering Game Mode...
> governor was initially set to [ondemand]
> Requesting update of governor policy to performance
> Setting governors to performance
> Setting scheduling policies...
> Client [24999] already reniced, ignoring.
> Setting client [24999] to SCHED_ISO failed with error 1, ignoring (your kernel may not support this).
> Adding game: 25041 [/usr/bin/bash]
> Setting scheduling policies...
> Client [25041] already reniced, ignoring.
> Setting client [25041] to SCHED_ISO failed with error 1, ignoring (your kernel may not support this).
> Adding game: 25042 [/usr/bin/pulseaudio]
> Setting scheduling policies...
> Client [25042] already reniced, ignoring.
> Setting client [25042] to SCHED_ISO failed with error 1, ignoring (your kernel may not support this).
> Removing game: 25042 [/usr/bin/pulseaudio]
> Removing game: 25041 [/usr/bin/bash]
>

**Comment by terencode** [comment] 2018-10-03 17:18
Why does it treat pulseaudio and bash as game though?

**Comment by kakra** [comment] 2018-10-03 17:20
Is that a SteamPlay game?

**Comment by terencode** [comment] 2018-10-03 17:20
no it's not.

**Comment by kakra** [comment] 2018-10-03 17:27
I'm currently working on a GameMode feature to add full Steam support, it should fix such issues then by using default blacklists...

Give me some time comparing your configuration dumps with my system and find where the differences may be.

**Comment by terencode** [comment] 2018-10-03 17:28
It seems I got it to work by disabling [Ananicy](https://github.com/Nefelim4ag/Ananicy).

**Comment by terencode** [comment] 2018-10-03 17:29
> Then it probably auto-spawns pulseaudio and you used LD_PRELOAD to add GameMode. 

Correct, I'll apply your suggestions while you're working on this full Steam support.

**Comment by terencode** [comment] 2018-10-03 17:31
Now we found the culprit, we need to figure out why it results on this type of error, either workaround it and if not possible, warn in the documentation it's not playing well with it and maybe add a way for the daemon to be aware of its presence and then print warning and only make cpu scheduler changes.

**Comment by terencode** [comment] 2018-10-03 17:41
blacklisting pulseaudio and bash is not working for me.

**Comment by kakra** [comment] 2018-10-03 17:42
Oh this looks easy now: Ananicy puts the Steam client into sched=idle. This will leak into processes started by Steam. You're usually not allowed to raise a process back to a higher scheduling class then. I'll try to check this. If this is true, the configuration shipped with Ananicy is fundamentally broken: The idle cpu class will leak into all games started. If the game is not actively detected by Ananicy, it will run with idle class. Not really the effect you want.

I'm not sure how Ananicy itself fixes this. Probably it's running as root and root is allowed to do such things.

Yep, just tested:

1. Start a process, get it's pid
2. Run `schedtool PID` to see current settings
3. Run `schedtool -D PID` to make it idle
4. Run `schedtool -I PID` to make it iso: Permission denied! Bang!

Good find!

**Comment by kakra** [comment] 2018-10-03 17:46
GameMode has a patch lately to not leak scheduler settings into children.

You actually don't need Ananicy if your kernel supports SCHED_ISO: The game will be set to iso through GameMode, and this means it will be scheduled before anything else, the Steam client can spend as much cpu cycles as it wants in the background, it won't hurt your game play at all.

**Comment by kakra** [comment] 2018-10-03 17:49
I'll create a log note for this in the code and I suppose we can close this issue then with such a follow-up PR? (leave it open until then)

**Comment by terencode** [comment] 2018-10-03 17:53
Nice, makes sense, I'll open an issue for Ananicy.
I'll close after the PR is merged then.

**Comment by kakra** [comment] 2018-10-03 17:54
The PR will close this automatically so you get notified when the change to the code is in.

**Comment by kakra** [comment] 2018-10-03 19:06
This is more a general design problem of such daemons due to how the kernel works, not necessarily a fundamental brokenness. I'm not sure if Ananicy can fix this as it is purely bash based and `schedtool` has no option for enabling `SCHED_RESET_ON_FORK`. Such daemons should actually not touch launcher shells at all. Also, putting Steam into `SCHED_IDLE` may have negative impact on how the game can interact with the Steam API and the Steam overlay as this surely interfaces with the running Steam client somehow, and Steam should provide quick replies here. It is fine to lower the priority of the Steam web helper, tho: It is unlikely to spawn any user-facing processes.

Very similar problems will arise with Ananicy because it puts Steam into a limited cgroup. Launched games will then share the same fate and end up there except Ananicy detects them and moves them to another group (the amount of detected games is actually very sparse). So, let's face it: Handling the main Steam client with Ananicy is at best probably a bad idea. It will always have to work against itself then. Similar rules apply for daemons like `verynice`, or if you had ideas like managing lower level process spawners like dbus, kio, ...

**Comment by kakra** [comment] 2018-10-03 19:12
@VanackSabbadium wrote:
> I've got the same problem, and i also add that GameMode can't renice processes.
> 
> `Renicing client [3499] failed with error 13, ignoring.`

Error 13 shouldn't happen - it's not documented in the man page of `sched_setscheduler`. This can only mean that GameMode and the game you're trying to manage, are running under different uids or in different namespaces (e.g. Flatpak, chroot, Docker).

**Comment by terencode** [comment] 2018-10-03 19:15
@kakra I'm having the same issue. How can I check if it's the case for me too?

**Comment by kakra** [comment] 2018-10-04 10:46
@terencode wrote:
> I'm having the same issue. How can I check if it's the case for me too?

Sorry for the delay, I think the answer is above if I understand the context right.

**Comment by terencode** [comment] 2018-10-04 17:11
No problem, I think you are correct. I would add *99-gamemode.conf*  and reference it in the README.md. This will make it easier for packaging.

**Comment by kakra** [comment] 2018-10-04 17:30
For packaging don't use 99 as prefix so the user can overwrite it easier with a higher number. Do you want to create a PR?

**Comment by terencode** [comment] 2018-10-04 17:32
Makes sense, ok I'll do it.

**Comment by kakra** [comment] 2018-10-04 17:34
Also, in the Gentoo ebuild I'm creating a new user group. So the file should be templated to replace the default group with a custom group easily. If you need help with the PR, I'll guide you. Just propose a PR and we can walk you through the rest.

**Comment by terencode** [comment] 2018-10-04 17:42
I've made the minimum at #85 so we can keep the discussion going there.

**Closed** 2018-10-08 16:30 UTC
